# Generated by Django 3.1.6 on 2021-02-14 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('archived', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField(max_length=3)),
                ('gender', models.PositiveSmallIntegerField(max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('cellphone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('instagram', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlatForm',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Web Client'), (0, 'Android'), (0, 'Iphone/Ipad')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=50)),
                ('target_gender', models.PositiveSmallIntegerField(max_length=1)),
                ('target_age', models.PositiveSmallIntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('archived', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField(max_length=3)),
                ('gender', models.PositiveSmallIntegerField(max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('cellphone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('instagram', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('archived', models.DateTimeField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=50)),
                ('cost', models.FloatField()),
                ('sale_price', models.FloatField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.brand')),
                ('categories', models.ManyToManyField(to='management.ProductCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('archived', models.DateTimeField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.PositiveSmallIntegerField(max_length=2)),
                ('amount', models.FloatField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.contact')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.platform')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.useraccount'),
        ),
    ]
